### ISSUE TITLE
pobj({'resp_body_bytes': b'&#39;c'}) when printed obj include escaped char

### ISSUE THREAD

**Issue by ihgazni2** [ihgazni2/dlixhict-didactic#4]
>>> pobj({'resp_body_bytes': b'\&\#39;c'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/xdict-0.01-py3.4.egg/xdict/jprint.py", line 1496, in pobj
  File "/usr/local/lib/python3.4/site-packages/xdict-0.01-py3.4.egg/xdict/jprint.py", line 1363, in print_j_str
  File "/usr/local/lib/python3.4/site-packages/xdict-0.01-py3.4.egg/xdict/jprint.py", line 1100, in get_line_color_sec
TypeError: 'NoneType' object is not subscriptable

**Comment by ihgazni2** [comment]
in get_print_lines_and_paths:
    741     #----------should not unescape here for secarino:{'resp_body_bytes': b'&#39;c'}
    742     #          which will cause {'resp_body_bytes': b''c'}
    743     new_lines[0] = orig_lines[0]
    744     #----------should not unescape here 
    745     paths = {}
    746     paths = {0: prev_path}
    747     for i in range(1, orig_lines.__len__()):
    748         curr_lv = int(j_lv_str[line_start_indexes[i]])
    749         curr_path = line_to_path(orig_lines[i],curr_lv,prev_lv,prev_path,block_op_pair     s_dict,sp,commas,colons)
    750         paths[i] = curr_path
    751         curr_head = utils.get_dir_string_head(curr_path,delimiter=sp).replace(sp,'')
    752         #---escaped to calculate the real prepend spaces
    753         curr_head = html.unescape(curr_head)
    754         #---escaped to calculate the real prepend spaces
    755         curr_head_len = curr_head.__len__()
    756         prepend = " " * curr_head_len
    757         #------------should not unescape here
    758         new_lines[i] = ''.join((prepend,orig_lines[i]))
    759         #------------should not unescape here


in get_dynamic_indent_j_str:
    1249             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1250             painted_string = html.unescape(painted_string)
    1251             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1252         else:
    1253             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1254             painted_string = html.unescape(line)
    1255             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})


in print_j_str:
    1377             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1378             painted_string = html.unescape(painted_string)
    1379             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1380         else:
    1381             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})
    1382             painted_string = html.unescape(line)
    1383             #-------fix issues--- when pobj({'resp_body_bytes': b'&#39;c'})

**Comment by ihgazni2** [comment]
fixed.
Python 3.4.2 (default, Oct 16 2014, 20:18:04) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xdict.jprint import pobj
>>> 
>>> pobj({'resp_body_bytes': b'&#39;c'})
{
 'resp_body_bytes': b''c'
}
>>> 
>>> exit()
